### ISSUE TITLE
Upgrade to newest xcode and flutter version

### ISSUE THREAD

**Issue by JulianBissekkou** [Rushabhshroff/flutter_system_proxy#18]
Apps using this package are not able to compile if the build is done with xcode 16.

```
❌  /ios/Classes/SwiftFlutterSystemProxyPlugin.swift:113:26: value of type 'CFRunLoopSource' has no member 'takeUnretainedValue'
            }, &context).takeUnretainedValue()
```

**Comment by oelburk** [comment]
Just got the same here!

**Comment by JulianBissekkou** [comment]
@oelburk 
You can test this change by doing:

```yaml

  flutter_system_proxy:
    git:
      url: https://github.com/tappeddev/flutter_system_proxy.git
      ref: 18-xcode-16-support
```
